### PR TITLE
Fix mismatch between CSSInterpolation and Interpolation<Props>

### LINKED ISSUE #3145: CSSInterpolation Type is Incompatible with CSS Prop
**Current behavior:**

An object of type `CSSInterpolation` can no longer be passed as the `css` prop. This was not the case prior to `@emotion/serialize@1.1.3`.

This is likely due to this recent change https://github.com/emotion-js/emotion/pull/3141

This can be resolved by also changing ArrayInterpolation from `Array<Interpolation<Props>>` to `ReadonlyArray<Interpolation<Props>> {}`.  However, I am unsure if this would cause other issues (I only tested using @emotion/react via CSS prop).

**To reproduce:**
Visit the repro below and hover over the CSS prop to see the following error:

```
Type 'CSSInterpolation' is not assignable to type 'Interpolation<Theme>'.
  Type 'ArrayCSSInterpolation' is not assignable to type 'Interpolation<Theme>'.
    Type 'readonly CSSInterpolation[]' is missing the following properties from type 'ArrayInterpolation<Theme>': pop, push, reverse, shift, and 6 more.
```

[Repro of issue](https://codesandbox.io/p/sandbox/emotion-issue-template-forked-xgz5wy?file=%2Fpackage.json%3A15%2C30&layout=%257B%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522rootPanelGroup%2522%253A%257B%2522direction%2522%253A%2522horizontal%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522id%2522%253A%2522ROOT_LAYOUT%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522UNKNOWN%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522clqwwrd0n00063b6j0uwodklm%2522%252C%2522sizes%2522%253A%255B70%252C30%255D%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522EDITOR%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522EDITOR%2522%252C%2522id%2522%253A%2522clqwwrd0m00023b6jfnii5d8s%2522%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522direction%2522%253A%2522horizontal%2522%252C%2522id%2522%253A%2522SHELLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522SHELLS%2522%252C%2522id%2522%253A%2522clqwwrd0n00033b6jmdr6ek4l%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%257D%252C%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522contentType%2522%253A%2522DEVTOOLS%2522%252C%2522id%2522%253A%2522clqwwrd0n00053b6jifdxu93l%2522%257D%255D%252C%2522sizes%2522%253A%255B100%255D%257D%255D%252C%2522sizes%2522%253A%255B50%252C50%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clqwwrd0m00023b6jfnii5d8s%2522%253A%257B%2522id%2522%253A%2522clqwwrd0m00023b6jfnii5d8s%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clqwwtrk400023b6j3i3x4tax%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A12%252C%2522startColumn%2522%253A116%252C%2522endLineNumber%2522%253A12%252C%2522endColumn%2522%253A116%257D%255D%252C%2522filepath%2522%253A%2522%252Fsrc%252FApp.tsx%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522id%2522%253A%2522clqwx5m8h00023b6j6n7p9bl0%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A15%252C%2522startColumn%2522%253A30%252C%2522endLineNumber%2522%253A15%252C%2522endColumn%2522%253A30%257D%255D%252C%2522filepath%2522%253A%2522%252Fpackage.json%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%252C%257B%2522id%2522%253A%2522clqwxdojs00023b6j6zz28v0x%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522type%2522%253A%2522FILE%2522%252C%2522initialSelections%2522%253A%255B%257B%2522startLineNumber%2522%253A14%252C%2522startColumn%2522%253A1%252C%2522endLineNumber%2522%253A14%252C%2522endColumn%2522%253A1%257D%255D%252C%2522filepath%2522%253A%2522%252Fsrc%252Findex.tsx%2522%252C%2522state%2522%253A%2522IDLE%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clqwx5m8h00023b6j6n7p9bl0%2522%257D%252C%2522clqwwrd0n00053b6jifdxu93l%2522%253A%257B%2522id%2522%253A%2522clqwwrd0n00053b6jifdxu93l%2522%252C%2522tabs%2522%253A%255B%257B%2522type%2522%253A%2522UNASSIGNED_PORT%2522%252C%2522port%2522%253A0%252C%2522id%2522%253A%2522clqwwto9a00bg3b6jo15fbrcs%2522%252C%2522mode%2522%253A%2522permanent%2522%252C%2522path%2522%253A%2522%252F%2522%257D%255D%252C%2522activeTabId%2522%253A%2522clqwwto9a00bg3b6jo15fbrcs%2522%257D%252C%2522clqwwrd0n00033b6jmdr6ek4l%2522%253A%257B%2522tabs%2522%253A%255B%255D%252C%2522id%2522%253A%2522clqwwrd0n00033b6jmdr6ek4l%2522%257D%257D%252C%2522showDevtools%2522%253Atrue%252C%2522showShells%2522%253Atrue%252C%2522showSidebar%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%257D)

**Expected behavior:**

This should not cause a TS issue.

**Environment information:**

- `react` version: 18.2.0
- `@emotion/react` version: 11.11.3

### PR DESCRIPTION
**Pull request by Cerber-Ursi**
**What**:

Eliminated types mismatch between `CSSInterpolation` (related to `csstypes`) and `Interpolation<Props>` (related to `emotion`'s own styled components machinery), which prevented the former from being used as the latter.

**Why**:

This fixes #3145.

**How**:

This required two different changes:
* Change type of `ArrayInterpolation`. Since it's expected that every interpolated value is treated by `emotion` as immutable, this change is correct, and it fixes the mismatch. At the same time, it breaks type inference on styled component creator functions, which required a second change.
* Change order of overloads for `styled.X` functions. The idea is that we want to use "template string tag" overload wherever possible and fall back to another one only for the explicit function calls. Previously, these two overloads were independent and the order didn't matter, but now, as every valid `TemplateStringsArray` is also a valid `ArrayInterpolation`, we need to explicitly prioritize the "template string tag" case.

**Checklist**:

- [ ] Documentation (N/A)
- [x] Tests
- [x] Code complete
- [x] Changeset

### CODE REVIEW

**Comment by mmarcuccio** [comment]
@emmatown do you happen to have time to review this PR?

**Comment by mmarcuccio** [comment]
@Andarist do you happen to have time to review this PR? Sorry for repeated tagging, but I don't want this effort to get lost 😄

**Review by tkh44 — APPROVED** [review]

File: packages/serialize/types/index.d.ts [hunk 1]
```diff
@@ -52,7 +52,7 @@ export type Keyframes = {
 } & string
 
 export interface ArrayInterpolation<Props>
-  extends Array<Interpolation<Props>> {}
+  extends ReadonlyArray<Interpolation<Props>> {}
```
Comment (Andarist) [inline packages/serialize/types/index.d.ts:55]: this makes sense to me, it shouldnt hurt us anyhow

File: packages/styled/types/base.d.ts [hunk 2]
```diff
@@ -63,10 +63,18 @@ export interface CreateStyledComponent<
   SpecificComponentProps extends {} = {},
   JSXProps extends {} = {}
 > {
+  (
+    template: TemplateStringsArray,
```
Comment (Andarist) [inline packages/styled/types/base.d.ts:67]: I see where you are going with this reordering and I think it makes sense. However, I'm really anxious about reordering those overloads. This change needs some extra coverage in our type tests.

Comment (Andarist) [reply packages/styled/types/base.d.ts:67]: Oh, I misunderstood this in part - this is actually a fix for existing tests (that became import after the change in `@emotion/serialize`)

File: .changeset/curly-planets-search.md [hunk 3]
```diff
@@ -0,0 +1,7 @@
+---
+'@emotion/react': patch
```
Comment (Andarist) [inline .changeset/curly-planets-search.md:2]:
```suggestion
```

File: .changeset/curly-planets-search.md [hunk 4]
```diff
@@ -0,0 +1,7 @@
...
+'@emotion/serialize': patch
+'@emotion/styled': patch
```
Comment (Andarist) [inline .changeset/curly-planets-search.md:4]:
```suggestion
```

File: .changeset/curly-planets-search.md [hunk 5]
```diff
@@ -0,0 +1,7 @@
...
+---
+
+Fix types mismatch between CSS interpolations and styled component creator functions
```
Comment (Andarist) [inline .changeset/curly-planets-search.md:7]:
```suggestion
Make `ArrayInterpolation` to extend `ReadonlyArray` to match a similar recent change to `ArrayCSSInterpolation`. It fixes some compatibility issues when those 2 get mixed together.
```

**Comment by valleywood** [comment]
@Cerber-Ursi @Andarist I believe this PR is related to this ticket 🤔 (haven't been able to verify): 
https://github.com/emotion-js/emotion/issues/3174

**Comment by Cerber-Ursi** [comment]
Thanks for notifying, will check soon. Seems that all this ReadonlyArray thing has quite a fallout actually...
