### PR TITLE
Fix typings of old packages

### LINKED ISSUE #914: Pre-commit hook is causing errors.
I actually have a bunch of issues with the pre-commit hook that makes automated changes (I assume applying Prettier recommendations?), but the majority are merely annoying, or opinions on Prettier settings, but I've discovered a case where **_these automated steps are actively breaking the codebase_**.

The file: `packages/create-emotion-server/types/index.d.ts` currently looks like this on `master`:
```
/// <reference types="node" />
// TypeScript Version: 2.3 

import { Emotion } from 'create-emotion';

export interface EmotionServer {
  extractCritical(html: string): { html: string; ids: string[]; css: string; };
  renderStylesToString(html: string): string;
  renderStylesToNodeStream(): NodeJS.ReadWriteStream;
}

export default function createEmotionServer(emotion: Emotion): EmotionServer;
```

If I try to add a space to the comment, and commit that change, then the pre-commit hook applies various automated changes, and results in a file that looks like this:

```
/// <reference types="node" />
// TypeScript Version: 2.3

import { Emotion } from 'create-emotion'

export interface EmotionServer {
  extractCritical(html: string): { html: string; ids: string[]; css: string }
  renderStylesToString(html: string): string
  renderStylesToNodeStream(): NodeJS.ReadWriteStream
}

export default function createEmotionServer(emotion: Emotion): EmotionServer
```

The main change appears to be the removal of all the semicolons.

Before the change `yarn test` runs smoothly.
After the change, but before committing `yarn test` runs smoothly.
After committing `yarn test` fails with: 
```
 RUNS  packages/styled/__tests__/styled.js
Parsing service failed to cat C:\Work\TwoGenerations\emotionPR\emotion\node_modules\@emotion\stylis\dist\stylis.esm.js, so skipping it. Exception: Sys_error("C:\\Work\\TwoGenerations\\emotionPR\\emotion\\node_modules\\@emotion\\stylis\\dist\\stylis.esm.js: No such file or directory")
Parsing service failed to cat C:\Work\TwoGenerations\emotionPR\emotion\node_modules\@emotion\stylis\dist\stylis.cjs.prod.js, so skipping it. Exception: Sys_error("C:\\Work\\TwoGenerations\\emotionPR\\emotion\\node_modules\\@emotion\\stylis\\dist\\stylis.cjs.prod.js: No such file or directory")
Parsing service failed to cat C:\Work\TwoGenerations\emotionPR\emotion\node_modules\@emotion\stylis\dist\stylis.cjs.js.flow, so skipping it. Exception: Sys_error("C:\\Work\\TwoGenerations\\emotionPR\\emotion\\node_modules\\@emotion\\stylis\\dist\\stylis.cjs.js.flow: No such file or directory")
Parsing service failed to cat C:\Work\TwoGenerations\emotionPR\emotion\node_modules\@emotion\stylis\dist\stylis.cjs.js, so skipping it. Exception: Sys_error("C:\\Work\\TwoGenerations\\emotionPR\\emotion\\node_modules\\@emotion\\stylis\\dist\\stylis.cjs.js: No such file or directory")
Parsing service failed to cat C:\Work\TwoGenerations\emotionPR\emotion\node_modules\@emotion\stylis\dist\stylis.cjs.dev.js, so skipping it. Exception: Sys_error("C:\\Work\\TwoGenerations\\emotionPR\\emotion\\node_modules\\@emotion\\stylis\\dist\\stylis.cjs.dev.js: No such file or directory")
Parsing service failed to cat C:\Work\TwoGenerations\emotionPR\emotion\node_modules\@emotion\stylis\dist\stylis.browser.cjs.js, so skipping it. Exception: Sys_error("C:\\Work\\TwoGenerations\\emotionPR\\emotion\\node_modules\\@emotion\\stylis\\dist\\stylis.browser.cjs.js: No such file or directory")
Parsing service failed to cat C:\Work\TwoGenerations\emotionPR\emotion\node_modules\@emotion\stylis\dist\index.min.js, so skipping it. Exception: Sys_error("C:\\Work\\TwoGenerations\\emotionPR\\emotion\\node_modules\\@emotion\\stylis\\dist\\index.min.js: No such file or directory")
create-emotion-server: Error: C:/Work/TwoGenerations/emotionPR/emotion/packages/create-emotion-server/types/index.d.ts:4:41
create-emotion-server: ERROR: 4:41   semicolon  Missing semicolon
create-emotion-server: ERROR: 10:50  semicolon  Missing semicolon
create-emotion-server: ERROR: 11:45  semicolon  Missing semicolon
create-emotion-server: ERROR: 12:53  semicolon  Missing semicolon
create-emotion-server: ERROR: 15:77  semicolon  Missing semicolon
create-emotion-server:     at C:\Work\TwoGenerations\emotionPR\emotion\packages\create-emotion-server\node_modules\dtslint\bin\index.js:101:19
create-emotion-server:     at Generator.next (<anonymous>)
create-emotion-server:     at fulfilled (C:\Work\TwoGenerations\emotionPR\emotion\packages\create-emotion-server\node_modules\dtslint\bin\index.js:5:58)
create-emotion-server: npm ERR! code ELIFECYCLE
create-emotion-server: npm ERR! errno 1
create-emotion-server: npm ERR! create-emotion-server@10.0.0-really-unsafe-please-do-not-use.2 test:typescript: `dtslint types`
create-emotion-server: npm ERR! Exit status 1
create-emotion-server: npm ERR!
create-emotion-server: npm ERR! Failed at the create-emotion-server@10.0.0-really-unsafe-please-do-not-use.2 test:typescript script.
create-emotion-server: npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
create-emotion-server: npm ERR! A complete log of this run can be found in:
create-emotion-server: npm ERR!     C:\Users\MDM\AppData\Roaming\npm-cache\_logs\2018-10-11T08_48_51_421Z-debug.log
lerna ERR! npm run test:typescript exited 1 in 'create-emotion-server'
lerna ERR! npm run test:typescript stdout:

> create-emotion-server@10.0.0-really-unsafe-please-do-not-use.2 test:typescript C:\Work\TwoGenerations\emotionPR\emotion\packages\create-emotion-server
> dtslint types


lerna ERR! npm run test:typescript stderr:
Error: C:/Work/TwoGenerations/emotionPR/emotion/packages/create-emotion-server/types/index.d.ts:4:41
ERROR: 4:41   semicolon  Missing semicolon
ERROR: 10:50  semicolon  Missing semicolon
ERROR: 11:45  semicolon  Missing semicolon
ERROR: 12:53  semicolon  Missing semicolon
ERROR: 15:77  semicolon  Missing semicolon

    at C:\Work\TwoGenerations\emotionPR\emotion\packages\create-emotion-server\node_modules\dtslint\bin\index.js:101:19
    at Generator.next (<anonymous>)
    at fulfilled (C:\Work\TwoGenerations\emotionPR\emotion\packages\create-emotion-server\node_modules\dtslint\bin\index.js:5:58)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! create-emotion-server@10.0.0-really-unsafe-please-do-not-use.2 test:typescript: `dtslint types`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the create-emotion-server@10.0.0-really-unsafe-please-do-not-use.2 test:typescript script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\MDM\AppData\Roaming\npm-cache\_logs\2018-10-11T08_48_51_421Z-debug.log

lerna ERR! npm run test:typescript exited 1 in 'create-emotion-server'
lerna WARN complete Waiting for 14 child processes to exit. CTRL-C to exit immediately.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
ERROR: "test:typescript" exited with 1.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

Full output file: 
[outputAfterGitCommitHookAutoChange.txt](https://github.com/emotion-js/emotion/files/2468241/outputAfterGitCommitHookAutoChange.txt)

Clearly the pre-commit hook should not _actively_ break the codebase :(

<hr>

 - emotion version: current master as of 11/10/2018
 - react version: (N/A: This is a bug with the library development, not its usage)
 - node version: `v10.10.1`
 - npm version: `6.4.1`
 - yarn version: `1.10.1`
 - git version: `2.19.1.windows.1`

### PR DESCRIPTION
**Pull request by Ailrun**
**What**: Typings of pre-typed packages

**Why**: It's broken after emotion@10

**How**: Using typings of `@emotion` scoped packages

**Checklist**:
- [N/A] Documentation
- [x] Tests
- [x] Code complete

Resolves #914.

### CODE REVIEW

File: packages/create-emotion-server/types/index.d.ts [hunk 1]
```diff
@@ -1,12 +1,19 @@
+// Definitions by: Junyoung Clare Jang <https://github.com/Ailrun>
+// TypeScript Version: 2.8
+
 /// <reference types="node" />
-// TypeScript Version: 2.3
+import { EmotionCache } from 'emotion'
 
-import { Emotion } from 'create-emotion';
+export interface EmotionCritical {
```
Comment (mitchellhamilton) [inline packages/create-emotion-server/types/index.d.ts]: Not a fan of this, why would someone want to use this interface?

File: packages/create-emotion/types/index.d.ts [hunk 2]
```diff
@@ -1,107 +1,53 @@
...
+  ): string
+  keyframes(...args: Array<Interpolation>): string
+  sheet: StyleSheet
+  caches: EmotionCache
+  merge(
+    registered: RegisteredCache,
+    css: (registeredStyles: Array<string>) => string,
+    className: string
+  ): string
+  getRegisteredStyles: typeof getRegisteredStyles
```
Comment (mitchellhamilton) [inline packages/create-emotion/types/index.d.ts]: The types of `merge` and `getRegisteredStyles` are wrong.

https://github.com/emotion-js/emotion/blob/master/packages/create-emotion/src/index.js#L132-L133

File: packages/emotion-theming/types/index.d.ts [hunk 3]
```diff
@@ -1,34 +1,29 @@
...
 export interface ThemeProviderProps<Theme> {
-    theme: Partial<Theme> | ((theme: Theme) => Theme);
+  theme: Partial<Theme> | ((outerTheme: Theme) => Theme)
 }
 
-export type ThemeProviderComponent<Theme> = ComponentClass<ThemeProviderProps<Theme>>;
-export const ThemeProvider: ThemeProviderComponent<object>;
+export function ThemeProvider<Theme>(
+  props: ThemeProviderProps<Theme>
+): React.ReactElement<any>
```
Comment (mitchellhamilton) [inline packages/emotion-theming/types/index.d.ts]: Why would someone want to provide a type to this? how would it actually give them any type safety? the current theming API is inherently not type safe so I'm not a huge fan of trying to add a bunch of types to it if it doesn't actually give any type safety

File: packages/emotion/types/index.d.ts [hunk 4]
```diff
@@ -1,17 +1,28 @@
 // Definitions by: Junyoung Clare Jang <https://github.com/Ailrun>
-// TypeScript Version: 2.3
+// TypeScript Version: 2.8
```
Comment (mitchellhamilton) [inline packages/emotion/types/index.d.ts]: What's the point of these comments?

File: packages/react-emotion/types/index.d.ts [hunk 5]
```diff
@@ -1,25 +1,17 @@
...
-export * from 'emotion';
-
-export type ThemedReactEmotionInterface<Theme extends object> = CreateStyled<Theme>;
+import styled from '@emotion/styled-base'
 
 export {
   CreateStyled,
+  CreateStyledComponentBase,
+  CreateStyledComponentExtrinsic,
+  CreateStyledComponentIntrinsic,
```
Comment (mitchellhamilton) [inline packages/react-emotion/types/index.d.ts]: I know these were added in a previous PR but what are they and what do they do?

File: packages/create-emotion/types/index.d.ts [hunk 6]
```diff
@@ -1,107 +1,53 @@
...
+    ...args: Array<Interpolation>
+  ): void
+  injectGlobal(...args: Array<Interpolation>): void
+  keyframes(
+    template: TemplateStringsArray,
+    ...args: Array<Interpolation>
+  ): string
+  keyframes(...args: Array<Interpolation>): string
+  sheet: StyleSheet
+  caches: EmotionCache
```
Comment (mitchellhamilton) [inline packages/create-emotion/types/index.d.ts]: This property is called `cache`.

File: packages/create-emotion-server/types/index.d.ts (hunk 1 above)
Comment (Ailrun) [reply packages/create-emotion-server/types/index.d.ts]: When someone want to type everything. For example, in following case.
```
const { html, ids, css }: EmotionCritical = emotionServer.extractCritical(renderedString);
const { html, ids, css }: { html: string; ids: Array<string>; css: string } = emotionServer.extractCritical(renderedString);
```
Second one is definitely more complex, IMO.

File: packages/create-emotion/types/index.d.ts (hunk 2 above)
Comment (Ailrun) [reply packages/create-emotion/types/index.d.ts]: Oh, I missed the parameters of bind. Thank you!

File: packages/emotion-theming/types/index.d.ts (hunk 3 above)
Comment (Ailrun) [reply packages/emotion-theming/types/index.d.ts]: It provides minimal type safety, namely, when one already has some `Theme` type,
`ThemeProvider<Theme>` will reject following cases. (Let's say `Subtype` as a subtype of `Theme`, and supertype as a supertype of `Theme`.)
```tsx
<ThemeProvider<Theme> theme={(outerTheme: Subtype): Supertype => { /* ... */ }}>
  {/* ... */}
</ThemeProvider>
```
```tsx
const superTheme: Supertype = /* ... */
<ThemeProvider<Theme> theme={superTheme}>
  {/* ... */}
</ThemeProvider>
```

File: packages/emotion/types/index.d.ts (hunk 4 above)
Comment (Ailrun) [reply packages/emotion/types/index.d.ts]: @mitchellhamilton dtslint parse these header comments, and check correctness of type for the version and above.

File: packages/react-emotion/types/index.d.ts (hunk 5 above)
Comment (Ailrun) [reply packages/react-emotion/types/index.d.ts]: @mitchellhamilton It's result of `styled(something)`.

File: packages/create-emotion/types/index.d.ts (hunk 6 above)
Comment (Ailrun) [reply packages/create-emotion/types/index.d.ts]: I'm confused with old typing. Thank you!

File: packages/create-emotion-server/types/index.d.ts (hunk 1 above)
Comment (mitchellhamilton) [reply packages/create-emotion-server/types/index.d.ts]: But why would anyone want to do that?

Comment (mitchellhamilton) [reply packages/create-emotion-server/types/index.d.ts]: It’s just more effort for no gain in type safety

Comment (Ailrun) [reply packages/create-emotion-server/types/index.d.ts]: @mitchellhamilton 
In TS, enforcing such rule does give some type safety sometimes, since TS does not infer type well just as flow does.
(Sometimes it infer weird, too wide, or too narrow type since it (usually) infers type not based on environment, but just based on the single statement)

Comment (Ailrun) [reply packages/create-emotion-server/types/index.d.ts]: @mitchellhamilton Actually, my team does 😃

Comment (mitchellhamilton) [reply packages/create-emotion-server/types/index.d.ts]: In this case, how would TS fail? I strongly disagree with that linting rule and I don’t think our types should be helping people do something which doesn’t actually help type safety and just adds more effort and makes the public API larger.

Comment (Ailrun) [reply packages/create-emotion-server/types/index.d.ts]: Of course it does not help only for this case.
However, for the rule generally, I think you cannot understand the rule since your background is flow. Flow has context-based type inference (which is muuuuuuuuuuch better than TS' type inference), but TS does not, so, in Flow,
```js
declare function fun(arg: 0 | 1 | 2): void;
let x = 2;
fun(x);
```
will just work:tm:. However, in TS, [similar example](https://www.typescriptlang.org/play/index.html#src=declare%20function%20fun(arg%3A%200%20%7C%201%20%7C%202)%3A%20void%3B%0D%0Alet%20x%20%3D%202%3B%0D%0Afun(x)%3B%0D%0Alet%20y%3A%202%20%3D%202%3B%0D%0Afun(y)%3B%0D%0A) does not work, where explicitly typed one works.

Comment (Ailrun) [reply packages/create-emotion-server/types/index.d.ts]: There are problem related with type generics too, but I cannot immediately create an example that works in flow but does not work in TS. (Usually, type generics case that does not work with TS is too complex to consider it as an example)
