### PR TITLE
Fix site buttons and remove `Links` from code example

### LINKED ISSUE #520: [Emotion Site] Link button styles not being applied
For some reason the styles for the link buttons on the [emotion.sh](https://emotion.sh) home page are not being applied until after you do an arbitrary change in the editor.

Alt Text

### PR DESCRIPTION
**Pull request by mitchellhamilton**
**What**:
Fix site buttons and remove Links from code example

**Why**:
Closes #520 
https://github.com/emotion-js/emotion/pull/519#discussion_r159985018

**How**:
Move the code examples on the homepage into a markdown file and query it so that the precompilation just works like the doc pages

**Checklist**:

- [ ] Documentation N/A
- [ ] Tests N/A
- [x] Code complete

### CODE REVIEW

File: packages/site/src/pages/index.js [hunk 1]
```diff
@@ -52,12 +46,20 @@ type State = {
...
 
 class IndexPage extends React.Component<Props, State> {
-  state = { mode: 'string', code: stringCode }
+  state = {
+    mode: 'string',
+    code: this.props.data.allMarkdownRemark.edges[0].node.hast.children[0]
+      .children[0].value
+  }
   render() {
+    const nodes = this.props.data.allMarkdownRemark.edges[0].node.hast.children
```
Comment (tkh44) [inline packages/site/src/pages/index.js]: `hast`? Not sure what it is just looks out of place

Comment (mitchellhamilton) [reply packages/site/src/pages/index.js]: https://github.com/syntax-tree/hast, It's how we can render custom components in markdown.
