### PR TITLE
Fix/1139

### LINKED ISSUE #1139: Dynamic Global styles with more than one rule crashing on updated
<!--
- `emotion` version: 10.0.5
- `react` version: 16.7.0

**Relevant code:**

```javascript
// Example usage
<Global
  styles={{
    body: { background: this.state.background },
    html: { color: this.state.color },
  }}
/>
```

**Reproduction:**

https://codesandbox.io/s/yw8lwvmr2v

**Problem description:**

When a Global component with dynamic styles (that may change depending on some variables) having more than one css rule gets updated, it crashes with the error message:

```
Uncaught DOMException: Failed to execute 'insertBefore' on 'Node': The node before which the new node is to be inserted is not a child of this node. (sheet.browser.esm.js:84)
```

**Suggested solution:**

It seems like [this line](https://github.com/emotion-js/emotion/blob/master/packages/core/src/global.js#L101) caused the problem.

 ```
let element = this.sheet.tags[0].nextElementSibling
```

Shouldn't this be `this.sheet.tags[this.sheet.tags.length - 1].nextElementSibling` instead?

### PR DESCRIPTION
**Pull request by Andarist**
fixes #1139

### CODE REVIEW

File: packages/core/__tests__/global.js [hunk 1]
```diff
@@ -2,15 +2,24 @@
...
-import { Global, keyframes, css } from '@emotion/core'
+import { Global, keyframes, css, withEmotionCache } from '@emotion/core'
 
-beforeEach(() => {
-  // $FlowFixMe
-  document.head.innerHTML = ''
+const ClearCache = withEmotionCache((props, cache) => {
+  cache.sheet.flush()
+  return null
+})
```
Comment (mitchellhamilton) [inline packages/core/__tests__/global.js]: I'd rather create a new cache in each test and pass it down with the CacheProvider and clear everything in the head in beforeEach
