### PR TITLE
Fix for opaque keyframes as object values

### LINKED ISSUE #1259: object style css not working with animations
- `emotion` version: 10.0.7
- `react` version: 16.8.3

**Relevant code:**

```javascript
/** @jsx jsx */
import { jsx, css, keyframes } from "@emotion/core";
import ReactDOM from "react-dom";

const kf = keyframes({
  from: {
    color: "back"
  },
  to: {
    color: "white"
  }
});

const blinkString = css`
  animation-name: ${kf};
  animation-duration: 1s;
  animation-iteration-count: infinite;
  animation-direction: alternate;
`;

const blinkObject = css({
  animationName: kf,
  animationDuration: "1s",
  animationIterationCount: "infinite",
  animationDirection: "alternate"
});

function App() {
  return (
    <div>
      <div css={blinkString}>I blink!</div>
      <div css={blinkObject}>I should blink, but do not!</div>
    </div>
  );
}

const rootElement = document.getElementById("root");
ReactDOM.render(<App />, rootElement);
```

**What you did:**

Used object style CSS with animations.

**What happened:**

No animation :(

**Reproduction:**

https://codesandbox.io/s/mqoow6yq1j

**Problem description:**

Seems like either there is a problem with animations when using object style or the docs need to be updated to show how to use animations with object style.

**Suggested solution:**

Not sure...

### PR DESCRIPTION
**Pull request by Andarist**
fixes #1259

Let's discuss the fix first, going to add changeset later.

### CODE REVIEW

File: packages/core/__tests__/keyframes.js [hunk 1]
```diff
@@ -113,6 +113,74 @@ cases(
...
+              animationName: animation,
+              animationDuration: '1s'
+            }}
+          >
+            {animation.name}
+          </div>
+        )
+      }
+    },
+    'object with animationName and string keyframes as value': {
```
Comment (Andarist) [inline packages/core/__tests__/keyframes.js]: this is a test covering previously uncovered (but working) situation

File: packages/serialize/src/index.js [hunk 2]
```diff
@@ -32,7 +32,7 @@ let processStyleValue = (
     case 'animation':
     case 'animationName': {
       if (typeof value === 'string') {
-        value = value.replace(animationRegex, (match, p1, p2) => {
+        return value.replace(animationRegex, (match, p1, p2) => {
```
Comment (Andarist) [inline packages/serialize/src/index.js]: just a short circuit

File: packages/serialize/src/index.js [hunk 3]
```diff
@@ -264,12 +264,22 @@ function createStringFromObject(
...
-          string += `${key}{${handleInterpolation(
+          const interpolated = handleInterpolation(
             mergedProps,
             registered,
             value,
             false
-          )}}`
+          )
+          switch (key) {
+            case 'animation':
```
Comment (mitchellhamilton) [inline packages/serialize/src/index.js]: This case will never happen

File: packages/core/__tests__/keyframes.js [hunk 4]
```diff
@@ -113,6 +113,74 @@ cases(
...
+          }
+          to {
+            color: hotpink;
+          }
+        `)
+
+        return (
+          <div
+            css={{
+              animation
```
Comment (mitchellhamilton) [inline packages/core/__tests__/keyframes.js]: This won't do anything, you need to at least also specify the duration of the animation. (hence the previous comment)

Comment (Andarist) [reply packages/core/__tests__/keyframes.js]: I can add animationDuration here to reflect better real-world scenario, but unfortunately animation can contain just an animation name and it's a valid CSS:
https://codesandbox.io/s/sad-cookies-oj0wk
